apiVersion: v1
kind: Secret
metadata:
  name: {{ include "contentbridge.fullname" . }}
  labels:
    {{- include "contentbridge.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.json: |-
    {
      "logger": {
        "level": "{{ .Values.contentbridge.logger.level }}"
      },
      "database": {
        "dialect": "{{ .Values.contentbridge.database.dialect }}",
        "host": "{{ .Values.contentbridge.database.host }}",
        "port": "{{ .Values.contentbridge.database.port }}",
        "username": "{{ .Values.contentbridge.database.username }}",
        "password": "{{ .Values.contentbridge.database.password }}",
        "database": "{{ .Values.contentbridge.database.database }}"
      },
      "jwt": {
        "algorithm": "{{ .Values.contentbridge.jwt.algorithm }}",
        "secret": "{{ .Values.contentbridge.jwt.secret }}",
        "expiresIn": "{{ .Values.contentbridge.jwt.expiresIn }}"
      }
    }
