apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: {{ .Release.Name }}-runner
  labels:
    {{- include "github-runner.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ .Release.Name }}-runner
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    - type: TotalNumberOfQueuedAndInProgressWorkflowRuns
      repositoryNames:
        - {{ .Values.github.repository }}
