apiVersion: v1
kind: Service
metadata:
  name: {{ include "tesbot.fullname" . }}
  labels:
    {{- include "tesbot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tesbot.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/type: webserver
