apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: shipevents.ship.glenndehaan.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: ship.glenndehaan.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                type:
                  type: string
                username:
                  type: string
                service:
                  type: string
                parameters:
                  type: object
                  properties:
                    image:
                      type: string
                    old_image_version:
                      type: string
                    new_image_version:
                      type: string
                    scale:
                      type: string
                time:
                  type: integer
  # either Namespaced or Cluster
  scope: Cluster
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: shipevents
    # singular name to be used as an alias on the CLI and for display
    singular: shipevent
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ShipEvent
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - se
