# Default values for telegram-pepperbot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of Telegram-Pepperbot replicas to deploy
replicaCount: 4
# -- Number of Telegram-Pepperbot revisions to keep
revisionHistoryLimit: 1

pepperbot:
  # -- Telegram-Pepperbot Redis Host
  redisHost: "redis-headless.example.svc.cluster.local"
  # -- Telegram-Pepperbot Telegram Bot Token
  telegramToken: ""
  # -- Telegram-Pepperbot Telegram Admin Chat ID (Allows specific people to run admin commands)
  telegramAdminChatId: ""
  # -- Telegram-Pepperbot Logger Level
  logLevel: "info"
  # -- Telegram-Pepperbot Deployment Toggles
  deployments:
    # -- Telegram-Pepperbot Enables/Disabled the message queuing deployment
    messageQueuing: true
    # -- Telegram-Pepperbot Enables/Disabled the bot commands deployment
    botCommands: true
    # -- Telegram-Pepperbot Enables/Disabled the bot consumer deployment
    botConsumer: true
    # -- Telegram-Pepperbot Enables/Disabled the webserver deployment
    webserver: true

image:
  # -- Telegram-Pepperbot image repository
  repository: marnixjanssen/telgram-pepperbot
  # -- Telegram-Pepperbot image pull policy
  pullPolicy: Always
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Specify docker-registry secret names as an array
imagePullSecrets: []
# -- String to partially override names.fullname
nameOverride: ""
# -- String to fully override names.fullname
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for Telegram-Pepperbot pods
podAnnotations: {}

# -- Pod Security Context for Telegram-Pepperbot pods
podSecurityContext: {}
  # fsGroup: 2000

# -- Security Context for Telegram-Pepperbot
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true

service:
  # -- Service type
  type: ClusterIP
  # -- Service HTTP port
  port: 8080

ingress:
  # -- Set to true to enable ingress record generation
  enabled: false
  # -- Set the ingressClassName on the ingress record for k8s 1.18+
  className: ""
  # -- Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations.
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    # -- Default host
    - host: telegram-pepperbot.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- TLS secret configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Resources for pods. Evaluated as a template.
resources:
  limits:
    memory: 25Mi
  requests:
    memory: 25Mi

# -- Node labels for pod assignment. Evaluated as a template.
nodeSelector: {}

# -- Tolerations for pod assignment. Evaluated as a template.
tolerations: []

# -- Affinity for pod assignment
affinity: {}
