{
 "title": "Loki / Global Metrics",
 "description": "Loki 2.0 metrics",
 "tags": [
  "loki",
  "logs"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Loki Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_build_info" }
   ]
  },
  {
   "title": "Message Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(loki_log_messages_total)" }
   ]
  },
  {
   "title": "Store Series Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "sum(loki_store_series_total)" }
   ]
  },
  {
   "title": "Store Chunks Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_ingester_chunk_stored_bytes_total)"
    }
   ]
  },
  {
   "title": "Panic ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "loki_panic_total" }
   ]
  },
  {
   "title": "API Request Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_request_duration_seconds_bucket[5m])) by (le,route))",
     "legendFormat": "{{ route }}"
    }
   ]
  },
  {
   "title": "LogQL Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_latency_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "LogQL  Processed bytes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_logql_querystats_bytes_processed_per_seconds_bucket[5m])) by (le,type))",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Received Lines / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_lines_received_total[5m]))",
     "legendFormat": "distributor / {{ tenant}}"
    }
   ]
  },
  {
   "title": "Distributor  Received bytes / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total[5m])) by (tenant)",
     "legendFormat": "distributor / {{tenant}}"
    }
   ]
  },
  {
   "title": "Batch Appends Sent to Ingesters / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_distributor_ingester_appends_total[5m])",
     "legendFormat": "successed"
    },
    {
     "expr": "loki_distributor_ingester_append_failures_total",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Store Series / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(loki_store_series_total[5m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Blocks / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_blocks_per_chunk_bucket[5m])) by (le))",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Chunk Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_size_bytes_bucket[5m])) by (le))",
     "legendFormat": "chunk size"
    }
   ]
  },
  {
   "title": "Chunk Age",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_age_seconds_bucket[5m])) by (le))",
     "legendFormat": "ages"
    }
   ]
  },
  {
   "title": "Chunk Compression Ratios",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_compression_ratio_bucket[5m])) by (le))",
     "legendFormat": "ratio"
    }
   ]
  },
  {
   "title": "Chunk Encode Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 29 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_encode_time_seconds_bucket[5m])) by (le))",
     "legendFormat": "durations."
    }
   ]
  },
  {
   "title": "Lines / Chunk",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(loki_ingester_chunk_entries_bucket[5m])) by (le))",
     "legendFormat": "lines"
    }
   ]
  },
  {
   "title": "Chunk Status",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_chunks_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "sum by (reason) (rate(loki_ingester_chunks_flushed_total[5m]))",
     "legendFormat": "flush / {{ reason }}"
    },
    {
     "expr": "sum by (fake) (rate(loki_ingester_chunks_stored_total[5m]))",
     "legendFormat": "stored"
    },
    {}
   ]
  },
  {
   "title": "Chunks in Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "loki_ingester_memory_chunks", "legendFormat": "chunks" }
   ]
  },
  {
   "title": "Chunks in Streams",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (tenan) (loki_ingester_memory_streams)",
     "legendFormat": "streams"
    }
   ]
  },
  {
   "title": "Strams Stats",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(loki_ingester_streams_created_total[5m])",
     "legendFormat": "create"
    },
    {
     "expr": "rate(loki_ingester_streams_removed_total[5m])",
     "legendFormat": "delete"
    }
   ]
  }
 ]
}