{{- if .Values.middlewares.ipWhitelist.enabled }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "traefik-helpers.fullname" . }}-ip-whitelist
  labels:
    {{- include "traefik-helpers.labels" . | nindent 4 }}
spec:
  {{- if not .Values.middlewares.ipWhitelist.options }}
  ipWhiteList: {}
  {{- else }}
  {{- with .Values.middlewares.ipWhitelist.options }}
  ipWhiteList:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
{{- end }}
