{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "traefik-redirect.fullname" . }}
  labels:
    {{- include "traefik-redirect.labels" . | nindent 4 }}
spec:
  secretName: {{ include "traefik-redirect.fullname" . }}-tls
  {{- with .Values.certManager.issuerRef }}
  issuerRef:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  dnsNames:
    - "{{ .Values.ingress.host }}"
{{- end }}
