apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "traefik-redirect.fullname" . }}
  labels:
    {{- include "traefik-redirect.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    secretName: {{ if eq .Values.ingress.tls.secretNameOverride "" }}{{ include "traefik-redirect.fullname" . }}-tls{{ else }}{{ .Values.ingress.tls.secretNameOverride }}{{ end }}
    {{- with .Values.ingress.tls.options }}
    options:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    domains:
      - main: {{ .Values.ingress.host }}
  {{- end }}
  {{- with .Values.ingress.entryPoints }}
  entryPoints:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  routes:
    - match: 'Host(`{{ .Values.ingress.host }}`) && PathPrefix(`/`)'
      kind: Rule
      middlewares:
        - name: {{ include "traefik-redirect.fullname" . }}
      services:
        - name: noop@internal
          kind: TraefikService
