---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-queuing-{{ include "telegram-pepperbot.fullname" . }}
  labels:
    {{- include "telegram-pepperbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "telegram-pepperbot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: message-queuing
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "telegram-pepperbot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: message-queuing
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "telegram-pepperbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-redis-ready
          image: busybox:1.35
          command: [ 'sh', '-c', 'echo -e "Checking for the availability of Redis Server"; while ! nc -z {{ .Values.pepperbot.redisHost }} 6379; do sleep 1; printf "-"; done; echo -e "  >> Redis Server is ready";' ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["dumb-init", "message-queuing"]
          env:
            - name: REDIS_URL
              value: "redis://{{ .Values.pepperbot.redisHost }}:6379"
            - name: TELOXIDE_TOKEN
              value: "{{ .Values.pepperbot.telegramToken }}"
            - name: ADMIN_CHAT_ID
              value: "{{ .Values.pepperbot.telegramAdminChatId }}"
            - name: RUST_LOG
              value: "{{ .Values.pepperbot.logLevel }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-commands-{{ include "telegram-pepperbot.fullname" . }}
  labels:
    {{- include "telegram-pepperbot.labels" . | nindent 4 }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "telegram-pepperbot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: bot-commands
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "telegram-pepperbot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: bot-commands
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "telegram-pepperbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-redis-ready
          image: busybox:1.35
          command: [ 'sh', '-c', 'echo -e "Checking for the availability of Redis Server"; while ! nc -z {{ .Values.pepperbot.redisHost }} 6379; do sleep 1; printf "-"; done; echo -e "  >> Redis Server is ready";' ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["dumb-init", "bot-commands"]
          env:
            - name: REDIS_URL
              value: "redis://{{ .Values.pepperbot.redisHost }}:6379"
            - name: TELOXIDE_TOKEN
              value: "{{ .Values.pepperbot.telegramToken }}"
            - name: ADMIN_CHAT_ID
              value: "{{ .Values.pepperbot.telegramAdminChatId }}"
            - name: RUST_LOG
              value: "{{ .Values.pepperbot.logLevel }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bot-consumer-{{ include "telegram-pepperbot.fullname" . }}
  labels:
    {{- include "telegram-pepperbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "telegram-pepperbot.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/type: bot-consumer
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "telegram-pepperbot.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/type: bot-consumer
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "telegram-pepperbot.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: {{ .Chart.Name }}-redis-ready
          image: busybox:1.35
          command: [ 'sh', '-c', 'echo -e "Checking for the availability of Redis Server"; while ! nc -z {{ .Values.pepperbot.redisHost }} 6379; do sleep 1; printf "-"; done; echo -e "  >> Redis Server is ready";' ]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["dumb-init", "bot-consumer"]
          env:
            - name: REDIS_URL
              value: "redis://{{ .Values.pepperbot.redisHost }}:6379"
            - name: TELOXIDE_TOKEN
              value: "{{ .Values.pepperbot.telegramToken }}"
            - name: ADMIN_CHAT_ID
              value: "{{ .Values.pepperbot.telegramAdminChatId }}"
            - name: RUST_LOG
              value: "{{ .Values.pepperbot.logLevel }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
