# Default values for kube-hook.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- Number of kube-hook replicas to deploy
replicaCount: 2
# -- Number of kube-hook revisions to keep
revisionHistoryLimit: 1

kubeHook:
  # -- kube-hook Namespace authentication tokens
  tokens: {}
#    - namespace: ""
#      token: ""

image:
  # -- kube-hook image repository
  repository: glenndehaan/kube-hook
  # -- kube-hook image pull policy
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: ""

# -- Specify docker-registry secret names as an array
imagePullSecrets: []
# -- String to partially override names.fullname
nameOverride: ""
# -- String to fully override names.fullname
fullnameOverride: ""

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

# -- Annotations for kube-hook pods
podAnnotations: {}

# -- Pod Security Context for kube-hook pods
podSecurityContext: {}
  # fsGroup: 2000

# -- Security Context for kube-hook
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsGroup: 101
  runAsUser: 101

service:
  # -- Service type
  type: ClusterIP
  # -- Service HTTP port
  port: 3000

ingress:
  # -- Set to true to enable ingress record generation
  enabled: false
  # -- Set the ingressClassName on the ingress record for k8s 1.18+
  className: ""
  # -- Additional annotations for the Ingress resource. To enable certificate autogeneration, place here your cert-manager annotations.
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    # -- Default host
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  # -- TLS secret configuration
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

# -- Resources for pods. Evaluated as a template.
resources:
  limits:
    memory: 125Mi
  requests:
    memory: 125Mi

# -- Node labels for pod assignment. Evaluated as a template.
nodeSelector: {}

# -- Tolerations for pod assignment. Evaluated as a template.
tolerations: []

# -- Affinity for pod assignment
affinity: {}
