{{- $fullName := include "sunflare-tools.fullname" . -}}
{{- $labels := include "sunflare-tools.labels" . -}}
{{- $selectorLabels := include "sunflare-tools.selectorLabels" . -}}
{{- range $t := .Values.sunflare.tools }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $t }}-{{ $fullName }}
  labels:
    {{- $labels | nindent 4 }}
spec:
  type: {{ $.Values.service.type }}
  ports:
    - port: {{ $.Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- $selectorLabels | nindent 4 }}
    app.kubernetes.io/type: {{ $t }}
---
{{- end }}
